// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCldp9LvUS64NhyPan_4bOynX2MfMf1yQ',
    appId: '1:889538796933:web:fc35622b4981a896d478ec',
    messagingSenderId: '889538796933',
    projectId: 'trackingworld-tw01',
    authDomain: 'trackingworld-tw01.firebaseapp.com',
    storageBucket: 'trackingworld-tw01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW1POxAaEQq7QmXL2vnwz1p88TLUlK4uI',
    appId: '1:889538796933:android:b9b9da2d43a2017fd478ec',
    messagingSenderId: '889538796933',
    projectId: 'trackingworld-tw01',
    storageBucket: 'trackingworld-tw01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwXn9VOklruVink94W-fxh94WzvuyR_Vs',
    appId: '1:889538796933:ios:889a58616974a38bd478ec',
    messagingSenderId: '889538796933',
    projectId: 'trackingworld-tw01',
    storageBucket: 'trackingworld-tw01.appspot.com',
    iosBundleId: 'com.example.trackingworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwXn9VOklruVink94W-fxh94WzvuyR_Vs',
    appId: '1:889538796933:ios:9c391d19b4c84437d478ec',
    messagingSenderId: '889538796933',
    projectId: 'trackingworld-tw01',
    storageBucket: 'trackingworld-tw01.appspot.com',
    iosBundleId: 'com.example.trackingworld.RunnerTests',
  );
}
